### ISSUE TITLE
Void Linux PPC: network not working

### ISSUE THREAD

**Issue by mehlon** [neagix/wii-linux-ngx#22]
Void Linux supports powerpc (unofficially). The `void-ppc-musl-ROOTFS-20190901.tar.xz` from their _Downloads_ boots fine on my Wii. 
However, it does not have `sshd` enabled by default,
does not have a `/etc/network/` directory.
Also, pressing the power button of the Wii once does not make it `poweroff` cleanly. 
USB Keyboard works fine.
Login with `root`:`voidlinux`

https://en.wikipedia.org/wiki/Void_Linux 
https://voidlinux.org/
https://voidlinux-ppc.org/

**Comment by mehlon** [comment]
To install packages onto the SD card changing root with QEMU works:
https://wiki.debian.org/QemuUserEmulation
https://unix.stackexchange.com/a/222981

**Comment by mehlon** [comment]
`connman` does not list any `technologies` (devices). So this means WiFi doesn't work on Void Linux by default. 
Does anyone know how this works on the Debian Jessie image?

**Comment by mehlon** [comment]
Running `conmmand` then `connmanctl technologies` strangely does not output anything now. But just then it showed something. I can't seem to replicate that.

**Comment by neagix** [comment]
@mehlon you should ask on Void Linux support forums/issue tracker about this.

This repository is about a customer kernel for the Wii and Void Linux is not using it.

**Comment by isometra** [comment]
I know I'm almost two years late, and I'm not sure if this comment fits here... but I hope it'll be helpful to anyone who stumbles across it.

I found a dirty workaround to get Void Linux working with Wi-Fi (because I didn't want to be stuck with Jessie's outdated packages). You can change the root from Debian Jessie to a Void filesystem by going through the regular chroot method. For me, I put the filesystem in a folder named `/chroot`, and took some of the steps from [the Debian wiki's "ChrootOnAndroid" page](https://wiki.debian.org/ChrootOnAndroid):
```
export ROOT=/chroot
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
export HOME=/root
for f in dev dev/pts proc sys ; do mount -o bind /$f $ROOT/$f ; done
chroot $ROOT /bin/bash -l
echo "nameserver 8.8.8.8" > /etc/resolv.conf
```

![Screenshot_2021-08-30_01-03-41](https://user-images.githubusercontent.com/55674863/131306780-fd35b9c7-442a-44be-9eb6-c82810c1fcbf.png)

I think it's still bound to Debian's overhead, and it's not a "full" system thanks to being under a chroot environment, but I find that it works surprisingly well for most packages. I say "most" because `bc` and `htop`(?) couldn't install under `ppc-musl` for me, but they installed under regular `ppc` just fine.
