### ISSUE TITLE
Wii-Linux-NGX running in PAL while console is NTSC-U/J

### ISSUE THREAD

**Issue by ghost** [neagix/wii-linux-ngx#34]
Hey, my Wii is trying to output as PAL when in Linux and is very glitchy when I get into Linux. 

AV to HDMI converter tells me it is outputting as NTSC443 (same thing as PAL60)

**Comment by isometra** [comment]
I hope this isn't a late response. I know what the problem could be!

[The bootloader (gumboot) defaults to running at PAL60.](https://github.com/neagix/wii-linux-ngx/blob/master/gumboot.lst) I edited the `gumboot.lst` file on my SD card (it should be on the FAT32 partition, in the "gumboot" folder), switched one of the first lines from `video PAL60` to `video PROGRESSIVE` and it works just fine.

Since you're using AV cables, I think you should switch it to `video NTSC` instead

I hope this isn't a messy explanation, I _really_ wanted to help a fellow Wii Linux user out
