### ISSUE TITLE
hardware acceleration? 

### ISSUE THREAD

**Issue by buddyjojo** [neagix/wii-linux-ngx#35]
I'm wondering if some kind of OpenGL hardware acceleration is possible.
looking online I can find a few old projects like [gl2gx](https://github.com/mvdhoning/gl2gx), [OpenGX](https://github.com/davidgfnet/opengx) and [this](https://www.phoronix.com/scan.php?page=news_item&px=NzAyMA).
Now I know all of those have been abandoned and I fully expect this to already have been discussed before but I cant really find anything on this topic so I might as well try to ask here.

edit: I just realized the things I linked might do the exact opposite of what I'm looking for.
Also, now that I'm thinking the stuff I linked doesn't even matter because that wold require whatever gpu driver the wii uses to be ported to the kernel?

**Comment by neagix** [comment]
It's not really clear what you are looking for; I would suggest checking out the capabilities of [libogc](https://wiibrew.org/wiki/Libogc) or a library like [this](http://forum.wiibrew.org/read.php?21,74603).

In both cases I don't think the kernel is involved at all because access to the video subsystem is not mediated by Mesa or any other Linux driver.

**Comment by buddyjojo** [comment]
I guess I was thinking of a drm kernel driver but I'm not exactly sure on how wii gpu hardware access works (I work with phones and even then I don't know much)

**Comment by buddyjojo** [comment]
But basically I am looking for any way of 3d? gpu acceleration

Those libs do seem like what I'm looking for but I guess a gx to gl wrapper would be required too

**Comment by neagix** [comment]
You are on the right track.
